- name: Initialize Kubernetes Master Node
  hosts: k8s-worker
  become: yes
  tasks:
      - name: Join worker nodes to the Kubernetes cluster
      command: "{{ hostvars['master1']['kubeadm_join_command'] }}"
      # Note: Ensure you replace 'master1' with the actual name of your master node in your inventory
